// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbtpymslbrrorsnvrvvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJidHB5bXNsYnJyb3JzbnZydnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDUyNTgsImV4cCI6MjA2OTcyMTI1OH0.nDzhCBe54wjiivRhqhdo9O0WlQdk4NN4Q9AukVQNdlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});