name: Deploy to S3

# This workflow:
# - Runs security checks on all PRs and pushes
# - Only deploys to S3 on pushes to main branch
# - Only runs deployment for PRs from habhabhabs user
# - Blocks deployment if security checks fail

# GitHub Secrets Required:
# - VITE_SUPABASE_URL (required)
# - VITE_SUPABASE_ANON_KEY (required) 
# - VITE_APP_URL (required)
# - AWS_ACCESS_KEY_ID (required)
# - AWS_SECRET_ACCESS_KEY (required)
# - S3_BUCKET_NAME (required)
# - CLOUDFRONT_DISTRIBUTION_ID (required)
# - VITE_GOOGLE_ANALYTICS_ID (optional)
# - VITE_GOOGLE_TAG_MANAGER_ID (optional)
# - VITE_FACEBOOK_PIXEL_ID (optional)
# - AWS_REGION (optional, defaults to us-east-1)
#
# See docs/GITHUB_SECRETS.md for complete setup instructions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Only run deployment for pushes to main or PRs from habhabhabs
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.actor == 'habhabhabs')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # Security checks before deployment
    - name: Run security scan
      run: npm run security:full

    - name: Run ESLint
      run: npm run lint

    # Only deploy if this is a push to main (not PRs)
    - name: Build application
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npm run build
      env:
        # Required Environment Variables
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_APP_URL: ${{ secrets.VITE_APP_URL }}
        
        # Optional Analytics Environment Variables
        VITE_GOOGLE_ANALYTICS_ID: ${{ secrets.VITE_GOOGLE_ANALYTICS_ID }}
        VITE_GOOGLE_TAG_MANAGER_ID: ${{ secrets.VITE_GOOGLE_TAG_MANAGER_ID }}
        VITE_FACEBOOK_PIXEL_ID: ${{ secrets.VITE_FACEBOOK_PIXEL_ID }}

    - name: Configure AWS credentials
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

    - name: Deploy to S3
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete --cache-control max-age=86400
        
    - name: Invalidate CloudFront
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

    - name: Health check
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        sleep 30
        curl -f ${{ secrets.VITE_APP_URL }} || exit 1